// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
pub const MATH_Q_BITS: i32 = 10;
pub const MATH_Q_SCALE: i32 = 1024;
pub const Q20_SCALE: i32 = 1048576;
pub const Q24_SCALE: i32 = 16777216;
pub const NATIVE_GRAVITY: i32 = -51;
pub const FNV64_OFFSET_BASIS: u64 = 14695981039346656037;
pub const FNV64_PRIME: u64 = 1099511628211;
pub const FNV64_MASK: u64 = 18446744073709551615;
pub const PHASE_TAU_DEPTH: i32 = 4;
pub const PHASE_LUT_SIZE: i32 = 256;
pub const PHASE_MAX_AMPLITUDE: u8 = 255;
pub const PHASE_MAX_LOCK: u8 = 255;
pub const PHASE_MAX_ENTANGLEMENT: u8 = 255;
pub const PHASE_HALF_PHASE: i32 = 128;
pub const PHASE_MIN_OMEGA: i16 = -16;
pub const PHASE_MAX_OMEGA: i16 = 16;
pub const PHASE_MAX_OMEGA_BRIDGE: i16 = 32;
pub const PHASE_FOSSILIZATION_PULSE_TICKS: i32 = 24;
pub const KURAMOTO_COUPLING_BASE: i32 = 1024;
pub const KURAMOTO_COUPLING_HARMONIC_PEER: i32 = 512;
pub const KURAMOTO_COUPLING_ANTIPODE: i32 = 358;
pub const KURAMOTO_COHERENCE_THRESHOLD_LOCK: i32 = 3072;
pub const KURAMOTO_COHERENCE_THRESHOLD_HIGH: i32 = 4300;
pub const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD: i32 = 614;
pub const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD: i32 = 942;
pub const KURAMOTO_COUPLING_PLASMID: i32 = 768;
pub const KURAMOTO_PLASMID_DIFFUSION_RATE: i32 = 51;
pub const MUTATION_BASE_COST: i32 = 50;
pub const MUTATION_MIN_COST: i32 = 5;
pub const MUTATION_MAX_COST: i32 = 500;
pub const MUTATION_SMOOTHING_FACTOR: i32 = 102;
pub const SENATE_ORACLE_TIMEOUT_MS: i32 = 16;
pub const SENATE_MYCELIUM_MIN_LOCKS: i32 = 1000;
pub const SENATE_MYCELIUM_MIN_ENERGY: i32 = 220;
pub const SENATE_SHADOW_BUCKET_MIN: i32 = 1000;
pub const SENATE_SHADOW_BUCKET_MAX: i32 = 1024;
pub const TISSUE_MORPHOLOGICAL_HYSTERESIS: i32 = 5;
pub const TISSUE_MORPHOLOGICAL_DELTA_MIN: i32 = 153;
/// Canonical Sakaguchi-Kuramoto phase lag for the production coupling law
/// (≈ 90°, the golden-angle compromise). Part of the LAW a ZK rollup proof
/// binds: the guest reads `alpha` from the wire and commits it in the public
/// values, so a proof states which coupling law it proved rather than being
/// assumed to have proved this one.
///
/// SSOT because it was not: the value 64 was a bare literal in four places
/// (`topology.rs`, `lib.rs`, and twice in `omega_zk_host`), which is how a
/// rollup proof came to be generated under `alpha: 0` while the canonical
/// lattice ran at 64 — the T3 crack. A literal cannot be kept in agreement with
/// three other literals.
pub const CANONICAL_PHASE_ALPHA: i32 = 64;

pub const BIOLOGY_SOMATIC_ALPHA: i32 = 1536;
pub const BIOLOGY_SOMATIC_DECAY_RATE: i32 = 51;
pub const BIOLOGY_SOMATIC_BASE_COST: i32 = 5;
pub const BIOLOGY_EXTINCTION_THRESHOLD: i32 = 0;
pub const BIOLOGY_APA_LEARNING_RATE: i32 = 51;
pub const BIOLOGY_APA_MEMORY_GAIN: i32 = 102;
pub const BIOLOGY_APA_DECISION_COST: i32 = 2;
pub const BIOLOGY_APA_COHERENCE_REWARD: i32 = 614;
pub const BIOLOGY_APA_MEMORY_DECAY: i32 = 1023;
pub const ADA_HODLER_BRAKE: i32 = 972;
pub const ADA_QE_STIMULUS_MAX: i32 = 500;
pub const ADA_QE_STIMULUS_MIN: i32 = 100;
pub const ADA_MASS_DILATION_MIN: i32 = 51;
pub const ADA_MASS_DILATION_MAX: i32 = 1024;
pub const ADA_MASS_DILATION_NUM: i32 = 3072;
pub const ORACLE_INVOCATION_COST: i32 = 10000;
pub const ORACLE_LEDGER_MAX_EVENTS: i32 = 1000;
pub const ORACLE_LEDGER_TRUNCATE: i32 = 800;
pub const ORACLE_MAX_SYSTEM_ENERGY: i32 = 21000000;
pub const ORACLE_BACKOFF_BASE_MS: i32 = 5000;
pub const ORACLE_BACKOFF_MAX_MS: i32 = 60000;
pub const ORACLE_AKASHIC_GC_THRESHOLD: i32 = 15000;
pub const ORACLE_AKASHIC_GC_TARGET: i32 = 8000;
pub const NETWORK_MYCELIUM_RATE_LIMIT: i32 = 50;
pub const NETWORK_WEBRTC_RECONNECT_CAP: i32 = 30000;
pub const NETWORK_MAX_PEERS_BUCKET: i32 = 3;
pub const WGSL_MYCELIAL_COUPLING: i32 = 4096;
pub const WGSL_STAKING_COUPLING: i32 = 3072;
pub const ESP_COUPLING_K_MIN: i32 = 10;
pub const ESP_COUPLING_K_MAX: i32 = 2048;
pub const ESP_MUTATION_RATE_MIN: i32 = 1;
pub const ESP_MUTATION_RATE_MAX: i32 = 102;
pub const ESP_DIFFUSION_RATE_MIN: i32 = 0;
pub const ESP_DIFFUSION_RATE_MAX: i32 = 1024;
pub const ESP_GLOBAL_ENERGY_CONSERVATION_ENFORCED: i32 = 1;
pub const MAX_ATP: u32 = 4096;
pub const BB_ENERGY_RANGE: u32 = 1024;
pub const BB_ENERGY_BASE: u32 = 128;
pub const BB_FREQ_RANGE: u32 = 4000;
pub const BB_FREQ_OFFSET: i32 = 2000;
pub const BB_FREQ_STEP: i32 = 1000;
pub const BB_FREQ_Q_SCALE: i32 = 1024;
pub const Q16_FACTOR_MITOSIS: u32 = 32768;
pub const MITOSIS_THRESHOLD: u32 = 2048;
pub const MITOSIS_COST: u32 = 1024;
pub const CHILD_ENERGY_SEED: u32 = 1024;
pub const PHASE_MASK_8BIT: u32 = 255;
pub const RESONANCE_PHASE_MODULUS: u32 = 64;
pub const CHRONOTOPOLOGY_STRESS_DIVISOR: u32 = 32;
pub const MAX_TIME_DILATION: u32 = 8;
pub const LANDAUER_BIT_COST: u32 = 1;
pub const STRUCTURAL_MAINTENANCE_DIVISOR: u32 = 8;
pub const STRESSOR_MIXER: u32 = 17;
pub const STRESSOR_MODULUS: u32 = 100;
pub const HOMEOSTASIS_Q_SHIFT: u32 = 10;
pub const PHASE_DRIFT_Q_SHIFT: u32 = 20;
pub const HEBBIAN_DEFAULT_WEIGHT: i32 = 1024;
pub const HEBBIAN_MAX_WEIGHT: i32 = 4096;
pub const DELTA_PHASE_DIVISOR: u32 = 8;
pub const Q16_FACTOR_SANCTUARY: u32 = 40000;
pub const SANCTUARY_ENERGY_THRESHOLD: u32 = 2500;
pub const Q16_FACTOR_ANCIENT_AGE: u32 = 163840;
pub const ANCIENT_AGE_TICKS: u32 = 10240;
pub const PREDATOR_ENERGY_STEAL: u32 = 5;
pub const DELTA_ENERGY_DIVISOR: u32 = 128;
pub const GOLDEN_TRACE_SAMPLES: u32 = 32;
