// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
export const MATH_Q_BITS = 10;
export const MATH_Q_SCALE = 1024;
export const NATIVE_GRAVITY = -0.05;
export const FNV64_OFFSET_BASIS = 14695981039346656037n;
export const FNV64_PRIME = 1099511628211n;
export const FNV64_MASK = 18446744073709551615n;
export const PHASE_TAU_DEPTH = 4;
export const PHASE_LUT_SIZE = 256;
export const PHASE_MAX_AMPLITUDE = 255;
export const PHASE_MAX_LOCK = 255;
export const PHASE_MAX_ENTANGLEMENT = 255;
export const PHASE_HALF_PHASE = 128;
export const PHASE_MIN_OMEGA = -16;
export const PHASE_MAX_OMEGA = 16;
export const PHASE_MAX_OMEGA_BRIDGE = 32;
export const PHASE_FOSSILIZATION_PULSE_TICKS = 24;
export const KURAMOTO_COUPLING_BASE = 1024;
export const KURAMOTO_COUPLING_HARMONIC_PEER = 512;
export const KURAMOTO_COUPLING_ANTIPODE = 358;
export const KURAMOTO_COHERENCE_THRESHOLD_LOCK = 3072;
export const KURAMOTO_COHERENCE_THRESHOLD_HIGH = 4301;
export const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD = 614;
export const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD = 942;
export const KURAMOTO_COUPLING_PLASMID = 768;
export const KURAMOTO_PLASMID_DIFFUSION_RATE = 51;
export const MUTATION_BASE_COST = 50;
export const MUTATION_MIN_COST = 5;
export const MUTATION_MAX_COST = 500;
export const MUTATION_SMOOTHING_FACTOR = 102;
export const SENATE_ORACLE_TIMEOUT_MS = 16;
export const SENATE_MYCELIUM_MIN_LOCKS = 1000;
export const SENATE_MYCELIUM_MIN_ENERGY = 220;
export const SENATE_SHADOW_BUCKET_MIN = 1000;
export const SENATE_SHADOW_BUCKET_MAX = 1024;
export const TISSUE_MORPHOLOGICAL_HYSTERESIS = 5;
export const TISSUE_MORPHOLOGICAL_DELTA_MIN = 154;
export const BIOLOGY_SOMATIC_ALPHA = 1.5;
export const BIOLOGY_SOMATIC_DECAY_RATE = 0.05;
export const BIOLOGY_SOMATIC_BASE_COST = 5;
export const BIOLOGY_EXTINCTION_THRESHOLD = 0;
export const ADA_HODLER_BRAKE = 0.95;
export const ADA_QE_STIMULUS_MAX = 500;
export const ADA_QE_STIMULUS_MIN = 100;
export const ADA_MASS_DILATION_MIN = 0.05;
export const ADA_MASS_DILATION_MAX = 1;
export const ADA_MASS_DILATION_NUM = 3;
export const ORACLE_INVOCATION_COST = 10000;
export const ORACLE_LEDGER_MAX_EVENTS = 1000;
export const ORACLE_LEDGER_TRUNCATE = 800;
export const ORACLE_MAX_SYSTEM_ENERGY = 21000000;
export const ORACLE_BACKOFF_BASE_MS = 5000;
export const ORACLE_BACKOFF_MAX_MS = 60000;
export const ORACLE_AKASHIC_GC_THRESHOLD = 15000;
export const ORACLE_AKASHIC_GC_TARGET = 8000;
export const NETWORK_MYCELIUM_RATE_LIMIT = 50;
export const NETWORK_WEBRTC_RECONNECT_CAP = 30000;
export const NETWORK_MAX_PEERS_BUCKET = 3;
export const WGSL_MYCELIAL_COUPLING = 4096;
export const WGSL_STAKING_COUPLING = 3072;

// --- MACROS ---
export function fast_abs(v: number): number {
    const mask = v >> 31;
    return (v ^ mask) - mask;
}

export function q20_round(x: number): number {
    return x >= 0 ? Math.floor((x + 524288) / 1048576) : Math.ceil((x - 524288) / 1048576);
}

export function sin_q10(from_theta: number, to_theta: number): number {
    const index = (to_theta + 256 - from_theta) % 256;
    return SINE_LUT[index];
}

export function cos_q10(from_theta: number, to_theta: number): number {
    const index = (to_theta + 256 - from_theta + 64) % 256;
    return SINE_LUT[index];
}

export function mix_u64(hash: bigint, value: bigint): bigint {
    const h = hash ^ value;
    return BigInt.asUintN(64, h * FNV64_PRIME);
}

export function wrap_index(value: number, modulo: number): number {
    return value & (modulo - 1);
}

export function signed_phase_delta(from_theta: number, to_theta: number): number {
    const delta = (to_theta - from_theta) & 255;
    return delta > 128 ? delta - 256 : delta;
}

export function phase_distance(a: number, b: number): number {
    const diff = fast_abs(a - b) & 255;
    return diff > 128 ? 256 - diff : diff;
}

export function clamp_i32(value: number, min_val: number, max_val: number): number {
    return Math.min(max_val, Math.max(min_val, value));
}

export function atan2_u8(y: number, x: number): number {
    if (x === 0 && y === 0) { return 0; }
        const abs_y = fast_abs(y);
        const abs_x = fast_abs(x);
        const a = Math.min(abs_y, abs_x);
        const b = Math.max(abs_y, abs_x);
        let ratio = b === 0 ? 0 : Math.floor((a * 128) / b);
        if (ratio > 128) { ratio = 128; }
        const octant_angle = ATAN_LUT[ratio];
        const quadrant_angle = abs_y > abs_x ? 64 - octant_angle : octant_angle;
        if (x < 0) {
            if (y < 0) { return (128 + quadrant_angle) & 255; } 
            else { return (128 - quadrant_angle) & 255; }
        } else {
            if (y < 0) { return (256 - quadrant_angle) & 255; } 
            else { return quadrant_angle & 255; }
        }
}

// --- HARDCODED LUTS ---
export const SINE_LUT = new Int32Array([
    0, 25, 50, 75, 100, 125, 150, 175, 200, 224, 249, 273, 297, 321, 345, 369,
    392, 415, 438, 460, 483, 505, 526, 548, 569, 590, 610, 630, 650, 669, 688, 706,
    724, 742, 759, 775, 792, 807, 822, 837, 851, 865, 878, 891, 903, 915, 926, 936,
    946, 955, 964, 972, 980, 987, 993, 999, 1004, 1009, 1013, 1016, 1019, 1021, 1023, 1024,
    1024, 1024, 1023, 1021, 1019, 1016, 1013, 1009, 1004, 999, 993, 987, 980, 972, 964, 955,
    946, 936, 926, 915, 903, 891, 878, 865, 851, 837, 822, 807, 792, 775, 759, 742,
    724, 706, 688, 669, 650, 630, 610, 590, 569, 548, 526, 505, 483, 460, 438, 415,
    392, 369, 345, 321, 297, 273, 249, 224, 200, 175, 150, 125, 100, 75, 50, 25,
    0, -25, -50, -75, -100, -125, -150, -175, -200, -224, -249, -273, -297, -321, -345, -369,
    -392, -415, -438, -460, -483, -505, -526, -548, -569, -590, -610, -630, -650, -669, -688, -706,
    -724, -742, -759, -775, -792, -807, -822, -837, -851, -865, -878, -891, -903, -915, -926, -936,
    -946, -955, -964, -972, -980, -987, -993, -999, -1004, -1009, -1013, -1016, -1019, -1021, -1023, -1024,
    -1024, -1024, -1023, -1021, -1019, -1016, -1013, -1009, -1004, -999, -993, -987, -980, -972, -964, -955,
    -946, -936, -926, -915, -903, -891, -878, -865, -851, -837, -822, -807, -792, -775, -759, -742,
    -724, -706, -688, -669, -650, -630, -610, -590, -569, -548, -526, -505, -483, -460, -438, -415,
    -392, -369, -345, -321, -297, -273, -249, -224, -200, -175, -150, -125, -100, -75, -50, -25,
]);

export const ENTROPY_LUT = new Int32Array([
    0, 32, 56, 77, 96, 114, 130, 145, 160, 174, 187, 200, 212, 224, 235, 246,
    256, 266, 276, 285, 294, 303, 312, 320, 328, 336, 343, 350, 358, 364, 371, 378,
    384, 390, 396, 402, 408, 413, 418, 423, 428, 433, 438, 443, 447, 451, 456, 460,
    464, 468, 471, 475, 478, 482, 485, 488, 491, 494, 497, 500, 502, 505, 507, 510,
    512, 514, 516, 518, 520, 522, 524, 525, 527, 529, 530, 531, 533, 534, 535, 536,
    537, 538, 539, 539, 540, 541, 541, 542, 542, 543, 543, 543, 543, 543, 543, 543,
    543, 543, 543, 543, 542, 542, 542, 541, 541, 540, 539, 539, 538, 537, 536, 535,
    534, 533, 532, 531, 530, 529, 527, 526, 525, 523, 522, 520, 519, 517, 515, 514,
    512, 510, 508, 506, 505, 503, 501, 499, 496, 494, 492, 490, 488, 485, 483, 481,
    478, 476, 473, 471, 468, 465, 463, 460, 457, 454, 452, 449, 446, 443, 440, 437,
    434, 431, 428, 425, 421, 418, 415, 412, 408, 405, 402, 398, 395, 391, 388, 384,
    381, 377, 373, 370, 366, 362, 358, 355, 351, 347, 343, 339, 335, 331, 327, 323,
    319, 315, 310, 306, 302, 298, 294, 289, 285, 281, 276, 272, 267, 263, 258, 254,
    249, 245, 240, 235, 231, 226, 221, 217, 212, 207, 202, 197, 192, 187, 183, 178,
    173, 168, 163, 157, 152, 147, 142, 137, 132, 127, 121, 116, 111, 105, 100, 95,
    89, 84, 79, 73, 68, 62, 57, 51, 45, 40, 34, 29, 23, 17, 11, 6,
]);

export const ATAN_LUT = new Uint8Array([
    0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5,
    5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10,
    10, 10, 11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14,
    15, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19,
    19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23,
    23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26,
    26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29,
    29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32,
    32,
]);

