// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
export const MATH_Q_BITS = 10;
export const MATH_Q_SCALE = 1024;
export const Q20_SCALE = 1048576;
export const Q24_SCALE = 16777216;
/**
 * Q10 fixed-point: -51/1024 ≈ -0.0498, i.e. ≈ -5% per tick. Negative = an
 * inward pull toward the torus centre. Reported as an unexplained magic
 * number; it is not empirical, it is -0.05 rounded down in Q10 — the same
 * 5% that ADA_MASS_DILATION_MIN (+51) expresses with the opposite sign.
 */
export const NATIVE_GRAVITY = -51;

export const FNV64_OFFSET_BASIS = 14695981039346656037n;
export const FNV64_PRIME = 1099511628211n;
export const FNV64_MASK = 18446744073709551615n;
export const PHASE_TAU_DEPTH = 4;
export const PHASE_LUT_SIZE = 256;
export const PHASE_MAX_AMPLITUDE = 255;
export const PHASE_MAX_LOCK = 255;
export const PHASE_MAX_ENTANGLEMENT = 255;
export const PHASE_HALF_PHASE = 128;
export const PHASE_MIN_OMEGA = -16;
export const PHASE_MAX_OMEGA = 16;
export const PHASE_MAX_OMEGA_BRIDGE = 32;
export const PHASE_FOSSILIZATION_PULSE_TICKS = 24;
export const KURAMOTO_COUPLING_BASE = 1024;
export const KURAMOTO_COUPLING_HARMONIC_PEER = 512;
export const KURAMOTO_COUPLING_ANTIPODE = 358;
export const KURAMOTO_COHERENCE_THRESHOLD_LOCK = 3072;
export const KURAMOTO_COHERENCE_THRESHOLD_HIGH = 4300;
export const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD = 614;
export const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD = 942;
export const KURAMOTO_COUPLING_PLASMID = 768;
export const KURAMOTO_PLASMID_DIFFUSION_RATE = 51;
export const MUTATION_BASE_COST = 50;
export const MUTATION_MIN_COST = 5;
export const MUTATION_MAX_COST = 500;
/**
 * Q10 fixed-point: 102/1024 ≈ 0.0996, i.e. a ≈10% exponential smoothing
 * coefficient on mutation cost. Deliberately kept as a literal rather than
 * `expr: MATH_Q_SCALE / 10` (which truncates to the same 102): 102 is what
 * the golden traces were recorded against, and the traces are the anchor.
 */
export const MUTATION_SMOOTHING_FACTOR = 102;

export const SENATE_ORACLE_TIMEOUT_MS = 16;
export const SENATE_MYCELIUM_MIN_LOCKS = 1000;
export const SENATE_MYCELIUM_MIN_ENERGY = 220;
export const SENATE_SHADOW_BUCKET_MIN = 1000;
export const SENATE_SHADOW_BUCKET_MAX = 1024;
export const TISSUE_MORPHOLOGICAL_HYSTERESIS = 5;
export const TISSUE_MORPHOLOGICAL_DELTA_MIN = 153;
/**
 * Canonical Sakaguchi-Kuramoto phase lag for the production coupling law
 * (≈ 90°, the golden-angle compromise). Part of the LAW a ZK rollup proof
 * binds: the guest reads `alpha` from the wire and commits it in the public
 * values, so a proof states which coupling law it proved rather than being
 * assumed to have proved this one.
 *
 * SSOT because it was not: the value 64 was a bare literal in four places
 * (`topology.rs`, `lib.rs`, and twice in `omega_zk_host`), which is how a
 * rollup proof came to be generated under `alpha: 0` while the canonical
 * lattice ran at 64 — the T3 crack. A literal cannot be kept in agreement
 * with three other literals.
 *
 * This note lived in the GENERATED constants.rs until 2026-08-06, i.e. in a
 * file marked DO NOT EDIT — as did the constant itself. Regenerating the
 * SSoT deleted both and broke the build of omega_v2 and omega_zk_host.
 */
export const CANONICAL_PHASE_ALPHA = 64;

export const BIOLOGY_SOMATIC_ALPHA = 1536;
export const BIOLOGY_SOMATIC_DECAY_RATE = 51;
export const BIOLOGY_SOMATIC_BASE_COST = 5;
export const BIOLOGY_EXTINCTION_THRESHOLD = 0;
export const BIOLOGY_APA_LEARNING_RATE = 51;
export const BIOLOGY_APA_MEMORY_GAIN = 102;
export const BIOLOGY_APA_DECISION_COST = 2;
export const BIOLOGY_APA_COHERENCE_REWARD = 614;
export const BIOLOGY_APA_MEMORY_DECAY = 1023;
/**
 * Q10 fixed-point: 972/1024 ≈ 0.9492, i.e. a ≈95% multiplier.
 *
 * UNREFERENCED: as of 2026-08-06 no code in omega_v2, omega_zk_host,
 * omega_zk_guest, src/, tools/ or tests/ reads this constant — it is
 * declared truth with no consumer. What behaviour it was meant to brake is
 * therefore not recoverable from the tree, and is deliberately NOT guessed
 * at here. Whoever revives it should write down the intent then.
 */
export const ADA_HODLER_BRAKE = 972;

export const ADA_QE_STIMULUS_MAX = 500;
export const ADA_QE_STIMULUS_MIN = 100;
export const ADA_MASS_DILATION_MIN = 51;
export const ADA_MASS_DILATION_MAX = 1024;
export const ADA_MASS_DILATION_NUM = 3072;
export const ORACLE_INVOCATION_COST = 10000;
export const ORACLE_LEDGER_MAX_EVENTS = 1000;
export const ORACLE_LEDGER_TRUNCATE = 800;
export const ORACLE_MAX_SYSTEM_ENERGY = 21000000;
export const ORACLE_BACKOFF_BASE_MS = 5000;
export const ORACLE_BACKOFF_MAX_MS = 60000;
export const ORACLE_AKASHIC_GC_THRESHOLD = 15000;
export const ORACLE_AKASHIC_GC_TARGET = 8000;
export const NETWORK_MYCELIUM_RATE_LIMIT = 50;
export const NETWORK_WEBRTC_RECONNECT_CAP = 30000;
export const NETWORK_MAX_PEERS_BUCKET = 3;
export const WGSL_MYCELIAL_COUPLING = 4096;
export const WGSL_STAKING_COUPLING = 3072;
export const ESP_COUPLING_K_MIN = 10;
export const ESP_COUPLING_K_MAX = 2048;
export const ESP_MUTATION_RATE_MIN = 1;
export const ESP_MUTATION_RATE_MAX = 102;
export const ESP_DIFFUSION_RATE_MIN = 0;
export const ESP_DIFFUSION_RATE_MAX = 1024;
export const ESP_GLOBAL_ENERGY_CONSERVATION_ENFORCED = 1;
export const MAX_ATP = 4096;
export const BB_ENERGY_RANGE = 1024;
export const BB_ENERGY_BASE = 128;
export const BB_FREQ_RANGE = 64;
export const BB_FREQ_OFFSET = 32;
export const BB_FREQ_STEP = 1000;
export const BB_FREQ_Q_SCALE = 1024;
export const Q16_FACTOR_MITOSIS = 32768;
export const MITOSIS_THRESHOLD = 2048;
export const MITOSIS_COST = 1024;
export const CHILD_ENERGY_SEED = 1024;
export const PHASE_MASK_8BIT = 255;
export const RESONANCE_PHASE_MODULUS = 64;
export const CHRONOTOPOLOGY_STRESS_DIVISOR = 32;
export const MAX_TIME_DILATION = 8;
export const LANDAUER_BIT_COST = 1;
export const STRUCTURAL_MAINTENANCE_DIVISOR = 8;
export const STRESSOR_MIXER = 17;
export const STRESSOR_MODULUS = 100;
export const HOMEOSTASIS_Q_SHIFT = 10;
export const PHASE_DRIFT_Q_SHIFT = 20;
export const HEBBIAN_DEFAULT_WEIGHT = 1024;
export const HEBBIAN_MAX_WEIGHT = 4096;
export const DELTA_PHASE_DIVISOR = 8;
export const Q16_FACTOR_SANCTUARY = 40000;
export const SANCTUARY_ENERGY_THRESHOLD = 2500;
export const Q16_FACTOR_ANCIENT_AGE = 163840;
export const ANCIENT_AGE_TICKS = 10240;
export const PREDATOR_ENERGY_STEAL = 5;
/**
 * Fraction of the allocated lattice that the Big Bang seeds with life (256/1024 = 25%). The rest is the room the world grows into. Ignition used to fill every slot, which made reproduction impossible by construction: mitosis places a child in a vacancy, a vacancy needs a death, and a world that starts full has neither. Empty Center, taken literally.
 */
export const BIG_BANG_SEED_DENSITY_Q10 = 256;

/**
 * Q10 ATP per living agent per tick at neutral sun (18432/1024 = 18); zero at midnight, 36 at noon. Calibrated by measurement, not taste (tools/ecology_probe.ts): at this yield the FITTEST agents reach the 2048 reproduction threshold and the rest do not, which is what makes an environment selective rather than merely survivable. Below it (9216) nobody approaches maturity; well above it every agent clears the bar at once and efficiency stops mattering. Note the homeostat pushes back: metabolic_pressure scales burn with the population's own average wealth, so yield and equilibrium are not proportional.
 */
export const SOLAR_YIELD_Q10 = 18432;

export const DELTA_ENERGY_DIVISOR = 128;
export const GOLDEN_TRACE_SAMPLES = 32;

// --- MACROS ---
export function fast_abs(v: number): number {
  const mask = v >> 31;
  return (v ^ mask) - mask;
}

export function mix_u64(hash: bigint, value: bigint): bigint {
  const h = hash ^ value;
  return BigInt.asUintN(64, h * FNV64_PRIME);
}

export function wrap_index(value: number, modulo: number): number {
  return value & (modulo - 1);
}

export function signed_phase_delta(
  from_theta: number,
  to_theta: number,
): number {
  const delta = (to_theta - from_theta) & 255;
  return delta > 128 ? delta - 256 : delta;
}

export function phase_distance(a: number, b: number): number {
  const diff = fast_abs(a - b) & 255;
  return diff > 128 ? 256 - diff : diff;
}

export function clamp_i32(
  value: number,
  min_val: number,
  max_val: number,
): number {
  return Math.min(max_val, Math.max(min_val, value));
}

// --- HARDCODED LUTS ---
