// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
pub const MATH_Q_BITS: i32 = 10;
pub const MATH_Q_SCALE: i32 = 1024;
pub const NATIVE_GRAVITY: i32 = -51;
pub const FNV64_OFFSET_BASIS: u64 = 14695981039346656037;
pub const FNV64_PRIME: u64 = 1099511628211;
pub const FNV64_MASK: u64 = 18446744073709551615;
pub const PHASE_TAU_DEPTH: i32 = 4;
pub const PHASE_LUT_SIZE: i32 = 256;
pub const PHASE_MAX_AMPLITUDE: u8 = 255;
pub const PHASE_MAX_LOCK: u8 = 255;
pub const PHASE_MAX_ENTANGLEMENT: u8 = 255;
pub const PHASE_HALF_PHASE: i32 = 128;
pub const PHASE_MIN_OMEGA: i16 = -16;
pub const PHASE_MAX_OMEGA: i16 = 16;
pub const PHASE_MAX_OMEGA_BRIDGE: i16 = 32;
pub const PHASE_FOSSILIZATION_PULSE_TICKS: i32 = 24;
pub const KURAMOTO_COUPLING_BASE: i32 = 1024;
pub const KURAMOTO_SAKAGUCHI_ALPHA: i32 = 38;
pub const KURAMOTO_COUPLING_HARMONIC_PEER: i32 = 512;
pub const KURAMOTO_COUPLING_ANTIPODE: i32 = 358;
pub const KURAMOTO_COHERENCE_THRESHOLD_LOCK: i32 = 3072;
pub const KURAMOTO_COHERENCE_THRESHOLD_HIGH: i32 = 4301;
pub const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD: i32 = 614;
pub const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD: i32 = 942;
pub const KURAMOTO_COUPLING_PLASMID: i32 = 768;
pub const KURAMOTO_PLASMID_DIFFUSION_RATE: i32 = 51;
pub const MUTATION_BASE_COST: i32 = 50;
pub const MUTATION_MIN_COST: i32 = 5;
pub const MUTATION_MAX_COST: i32 = 500;
pub const MUTATION_SMOOTHING_FACTOR: i32 = 102;
pub const SENATE_ORACLE_TIMEOUT_MS: i32 = 16;
pub const SENATE_MYCELIUM_MIN_LOCKS: i32 = 1000;
pub const SENATE_MYCELIUM_MIN_ENERGY: i32 = 220;
pub const SENATE_SHADOW_BUCKET_MIN: i32 = 1000;
pub const SENATE_SHADOW_BUCKET_MAX: i32 = 1024;
pub const TISSUE_MORPHOLOGICAL_HYSTERESIS: i32 = 5;
pub const TISSUE_MORPHOLOGICAL_DELTA_MIN: i32 = 154;
pub const BIOLOGY_SOMATIC_ALPHA: i32 = 1536;
pub const BIOLOGY_SOMATIC_DECAY_RATE: i32 = 51;
pub const BIOLOGY_SOMATIC_BASE_COST: i32 = 5;
pub const BIOLOGY_EXTINCTION_THRESHOLD: i32 = 0;
pub const BIOLOGY_APA_LEARNING_RATE: i32 = 51;
pub const BIOLOGY_APA_MEMORY_GAIN: i32 = 102;
pub const BIOLOGY_APA_DECISION_COST: i32 = 2;
pub const BIOLOGY_APA_COHERENCE_REWARD: i32 = 614;
pub const BIOLOGY_APA_MEMORY_DECAY: i32 = 1023;
pub const ADA_HODLER_BRAKE: i32 = 972;
pub const ADA_QE_STIMULUS_MAX: i32 = 500;
pub const ADA_QE_STIMULUS_MIN: i32 = 100;
pub const ADA_MASS_DILATION_MIN: i32 = 51;
pub const ADA_MASS_DILATION_MAX: i32 = 1024;
pub const ADA_MASS_DILATION_NUM: i32 = 3072;
pub const ORACLE_INVOCATION_COST: i32 = 10000;
pub const ORACLE_LEDGER_MAX_EVENTS: i32 = 1000;
pub const ORACLE_LEDGER_TRUNCATE: i32 = 800;
pub const ORACLE_MAX_SYSTEM_ENERGY: i32 = 21000000;
pub const ORACLE_BACKOFF_BASE_MS: i32 = 5000;
pub const ORACLE_BACKOFF_MAX_MS: i32 = 60000;
pub const ORACLE_AKASHIC_GC_THRESHOLD: i32 = 15000;
pub const ORACLE_AKASHIC_GC_TARGET: i32 = 8000;
pub const NETWORK_MYCELIUM_RATE_LIMIT: i32 = 50;
pub const NETWORK_WEBRTC_RECONNECT_CAP: i32 = 30000;
pub const NETWORK_MAX_PEERS_BUCKET: i32 = 3;
pub const WGSL_MYCELIAL_COUPLING: i32 = 4096;
pub const WGSL_STAKING_COUPLING: i32 = 3072;
pub const ESP_COUPLING_K_MIN: i32 = 10;
pub const ESP_COUPLING_K_MAX: i32 = 2048;
pub const ESP_MUTATION_RATE_MIN: i32 = 1;
pub const ESP_MUTATION_RATE_MAX: i32 = 102;
pub const ESP_DIFFUSION_RATE_MIN: i32 = 0;
pub const ESP_DIFFUSION_RATE_MAX: i32 = 1024;
pub const ESP_GLOBAL_ENERGY_CONSERVATION_ENFORCED: i32 = 1;

// --- MACROS ---
#[inline(always)]
pub fn fast_abs(v: i32) -> i32 {
    let mask = v >> 31;
    (v ^ mask) - mask
}

#[inline(always)]
pub fn q20_round(x: i32) -> i32 {
    if x >= 0 { (x + 524288) / 1048576 } else { (x - 524288) / 1048576 }
}

#[inline(always)]
pub fn sin_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta as u32 + 256 - from_theta as u32) % 256;
    SINE_LUT[index as usize]
}

#[inline(always)]
pub fn cos_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta as u32 + 256 - from_theta as u32 + 64) % 256;
    SINE_LUT[index as usize]
}

#[inline(always)]
pub fn mix_u64(hash: u64, value: u64) -> u64 {
    let h = hash ^ value;
    h.wrapping_mul(FNV64_PRIME)
}

#[inline(always)]
pub fn wrap_index(value: i32, modulo: i32) -> i32 {
    value & (modulo - 1)
}

#[inline(always)]
pub fn signed_phase_delta(from_theta: i32, to_theta: i32) -> i32 {
    let delta = (to_theta - from_theta) & 255;
    if delta > 128 { delta - 256 } else { delta }
}

#[inline(always)]
pub fn phase_distance(a: i32, b: i32) -> i32 {
    let diff = fast_abs(a - b) & 255;
    if diff > 128 { 256 - diff } else { diff }
}

#[inline(always)]
pub fn clamp_i32(value: i32, min_val: i32, max_val: i32) -> i32 {
    value.clamp(min_val, max_val)
}

#[inline(always)]
pub fn atan2_u8(y: i32, x: i32) -> u8 {
    if x == 0 && y == 0 { return 0; }
        let abs_y = fast_abs(y);
        let abs_x = fast_abs(x);
        let a = abs_y.min(abs_x);
        let b = abs_y.max(abs_x);
        let mut ratio = if b == 0 { 0 } else { (a * 128) / b };
        if ratio > 128 { ratio = 128; }
        let octant_angle = ATAN_LUT[ratio as usize];
        let quadrant_angle = if abs_y > abs_x { 64 - octant_angle } else { octant_angle };
        if x < 0 {
            if y < 0 { 128u8.wrapping_add(quadrant_angle) } else { 128u8.wrapping_sub(quadrant_angle) }
        } else {
            if y < 0 { 256u16.wrapping_sub(quadrant_angle as u16) as u8 } else { quadrant_angle }
        }
}

// --- HARDCODED LUTS ---
pub const SINE_LUT: [i32; 256] = [
    0, 25, 50, 75, 100, 125, 150, 175, 200, 224, 249, 273, 297, 321, 345, 369,
    392, 415, 438, 460, 483, 505, 526, 548, 569, 590, 610, 630, 650, 669, 688, 706,
    724, 742, 759, 775, 792, 807, 822, 837, 851, 865, 878, 891, 903, 915, 926, 936,
    946, 955, 964, 972, 980, 987, 993, 999, 1004, 1009, 1013, 1016, 1019, 1021, 1023, 1024,
    1024, 1024, 1023, 1021, 1019, 1016, 1013, 1009, 1004, 999, 993, 987, 980, 972, 964, 955,
    946, 936, 926, 915, 903, 891, 878, 865, 851, 837, 822, 807, 792, 775, 759, 742,
    724, 706, 688, 669, 650, 630, 610, 590, 569, 548, 526, 505, 483, 460, 438, 415,
    392, 369, 345, 321, 297, 273, 249, 224, 200, 175, 150, 125, 100, 75, 50, 25,
    0, -25, -50, -75, -100, -125, -150, -175, -200, -224, -249, -273, -297, -321, -345, -369,
    -392, -415, -438, -460, -483, -505, -526, -548, -569, -590, -610, -630, -650, -669, -688, -706,
    -724, -742, -759, -775, -792, -807, -822, -837, -851, -865, -878, -891, -903, -915, -926, -936,
    -946, -955, -964, -972, -980, -987, -993, -999, -1004, -1009, -1013, -1016, -1019, -1021, -1023, -1024,
    -1024, -1024, -1023, -1021, -1019, -1016, -1013, -1009, -1004, -999, -993, -987, -980, -972, -964, -955,
    -946, -936, -926, -915, -903, -891, -878, -865, -851, -837, -822, -807, -792, -775, -759, -742,
    -724, -706, -688, -669, -650, -630, -610, -590, -569, -548, -526, -505, -483, -460, -438, -415,
    -392, -369, -345, -321, -297, -273, -249, -224, -200, -175, -150, -125, -100, -75, -50, -25,
];

pub const ENTROPY_LUT: [i32; 256] = [
    0, 32, 56, 77, 96, 114, 130, 145, 160, 174, 187, 200, 212, 224, 235, 246,
    256, 266, 276, 285, 294, 303, 312, 320, 328, 336, 343, 350, 358, 364, 371, 378,
    384, 390, 396, 402, 408, 413, 418, 423, 428, 433, 438, 443, 447, 451, 456, 460,
    464, 468, 471, 475, 478, 482, 485, 488, 491, 494, 497, 500, 502, 505, 507, 510,
    512, 514, 516, 518, 520, 522, 524, 525, 527, 529, 530, 531, 533, 534, 535, 536,
    537, 538, 539, 539, 540, 541, 541, 542, 542, 543, 543, 543, 543, 543, 543, 543,
    543, 543, 543, 543, 542, 542, 542, 541, 541, 540, 539, 539, 538, 537, 536, 535,
    534, 533, 532, 531, 530, 529, 527, 526, 525, 523, 522, 520, 519, 517, 515, 514,
    512, 510, 508, 506, 505, 503, 501, 499, 496, 494, 492, 490, 488, 485, 483, 481,
    478, 476, 473, 471, 468, 465, 463, 460, 457, 454, 452, 449, 446, 443, 440, 437,
    434, 431, 428, 425, 421, 418, 415, 412, 408, 405, 402, 398, 395, 391, 388, 384,
    381, 377, 373, 370, 366, 362, 358, 355, 351, 347, 343, 339, 335, 331, 327, 323,
    319, 315, 310, 306, 302, 298, 294, 289, 285, 281, 276, 272, 267, 263, 258, 254,
    249, 245, 240, 235, 231, 226, 221, 217, 212, 207, 202, 197, 192, 187, 183, 178,
    173, 168, 163, 157, 152, 147, 142, 137, 132, 127, 121, 116, 111, 105, 100, 95,
    89, 84, 79, 73, 68, 62, 57, 51, 45, 40, 34, 29, 23, 17, 11, 6,
];

pub const ATAN_LUT: [u8; 129] = [
    0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5,
    5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10,
    10, 10, 11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14,
    15, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19,
    19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23,
    23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26,
    26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29,
    29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32,
    32,
];

