// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
pub const MATH_Q_BITS: i32 = 10;
pub const MATH_Q_SCALE: i32 = 1024;
pub const NATIVE_GRAVITY: f32 = -0.05;
pub const FNV64_OFFSET_BASIS: u64 = 14695981039346656037;
pub const FNV64_PRIME: u64 = 1099511628211;
pub const FNV64_MASK: u64 = 18446744073709551615;
pub const PHASE_TAU_DEPTH: i32 = 4;
pub const PHASE_LUT_SIZE: i32 = 256;
pub const PHASE_MAX_AMPLITUDE: u8 = 255;
pub const PHASE_MAX_LOCK: u8 = 255;
pub const PHASE_MAX_ENTANGLEMENT: u8 = 255;
pub const PHASE_HALF_PHASE: i32 = 128;
pub const PHASE_MIN_OMEGA: i16 = -16;
pub const PHASE_MAX_OMEGA: i16 = 16;
pub const PHASE_MAX_OMEGA_BRIDGE: i16 = 32;
pub const PHASE_FOSSILIZATION_PULSE_TICKS: i32 = 24;
pub const KURAMOTO_COUPLING_BASE: i32 = 1024;
pub const KURAMOTO_COUPLING_HARMONIC_PEER: i32 = 512;
pub const KURAMOTO_COUPLING_ANTIPODE: i32 = 358;
pub const KURAMOTO_COHERENCE_THRESHOLD_LOCK: i32 = 3072;
pub const KURAMOTO_COHERENCE_THRESHOLD_HIGH: i32 = 4301;
pub const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD: i32 = 614;
pub const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD: i32 = 942;
pub const KURAMOTO_COUPLING_PLASMID: i32 = 768;
pub const KURAMOTO_PLASMID_DIFFUSION_RATE: i32 = 51;
pub const MUTATION_BASE_COST: i32 = 50;
pub const MUTATION_MIN_COST: i32 = 5;
pub const MUTATION_MAX_COST: i32 = 500;
pub const MUTATION_SMOOTHING_FACTOR: i32 = 102;
pub const SENATE_ORACLE_TIMEOUT_MS: i32 = 16;
pub const SENATE_MYCELIUM_MIN_LOCKS: i32 = 1000;
pub const SENATE_MYCELIUM_MIN_ENERGY: i32 = 220;
pub const SENATE_SHADOW_BUCKET_MIN: i32 = 1000;
pub const SENATE_SHADOW_BUCKET_MAX: i32 = 1024;
pub const TISSUE_MORPHOLOGICAL_HYSTERESIS: i32 = 5;
pub const TISSUE_MORPHOLOGICAL_DELTA_MIN: i32 = 154;

// --- MACROS ---
#[inline(always)]
pub fn fast_abs(v: i32) -> i32 {
    let mask = v >> 31;
    (v ^ mask) - mask
}

#[inline(always)]
pub fn q20_round(x: i32) -> i32 {
    if x >= 0 { (x + 524288) / 1048576 } else { (x - 524288) / 1048576 }
}

#[inline(always)]
pub fn sin_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta as u32 + 256 - from_theta as u32) % 256;
    SINE_LUT[index as usize]
}

#[inline(always)]
pub fn cos_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta as u32 + 256 - from_theta as u32 + 64) % 256;
    SINE_LUT[index as usize]
}

// --- HARDCODED LUTS ---
pub const SINE_LUT: [i32; 256] = [
    0, 25, 50, 75, 100, 125, 150, 175, 200, 224, 249, 273, 297, 321, 345, 369,
    392, 415, 438, 460, 483, 505, 526, 548, 569, 590, 610, 630, 650, 669, 688, 706,
    724, 742, 759, 775, 792, 807, 822, 837, 851, 865, 878, 891, 903, 915, 926, 936,
    946, 955, 964, 972, 980, 987, 993, 999, 1004, 1009, 1013, 1016, 1019, 1021, 1023, 1024,
    1024, 1024, 1023, 1021, 1019, 1016, 1013, 1009, 1004, 999, 993, 987, 980, 972, 964, 955,
    946, 936, 926, 915, 903, 891, 878, 865, 851, 837, 822, 807, 792, 775, 759, 742,
    724, 706, 688, 669, 650, 630, 610, 590, 569, 548, 526, 505, 483, 460, 438, 415,
    392, 369, 345, 321, 297, 273, 249, 224, 200, 175, 150, 125, 100, 75, 50, 25,
    0, -25, -50, -75, -100, -125, -150, -175, -200, -224, -249, -273, -297, -321, -345, -369,
    -392, -415, -438, -460, -483, -505, -526, -548, -569, -590, -610, -630, -650, -669, -688, -706,
    -724, -742, -759, -775, -792, -807, -822, -837, -851, -865, -878, -891, -903, -915, -926, -936,
    -946, -955, -964, -972, -980, -987, -993, -999, -1004, -1009, -1013, -1016, -1019, -1021, -1023, -1024,
    -1024, -1024, -1023, -1021, -1019, -1016, -1013, -1009, -1004, -999, -993, -987, -980, -972, -964, -955,
    -946, -936, -926, -915, -903, -891, -878, -865, -851, -837, -822, -807, -792, -775, -759, -742,
    -724, -706, -688, -669, -650, -630, -610, -590, -569, -548, -526, -505, -483, -460, -438, -415,
    -392, -369, -345, -321, -297, -273, -249, -224, -200, -175, -150, -125, -100, -75, -50, -25,
];

pub const ENTROPY_LUT: [i32; 256] = [
    0, 32, 56, 77, 96, 114, 130, 145, 160, 174, 187, 200, 212, 224, 235, 246,
    256, 266, 276, 285, 294, 303, 312, 320, 328, 336, 343, 350, 358, 364, 371, 378,
    384, 390, 396, 402, 408, 413, 418, 423, 428, 433, 438, 443, 447, 451, 456, 460,
    464, 468, 471, 475, 478, 482, 485, 488, 491, 494, 497, 500, 502, 505, 507, 510,
    512, 514, 516, 518, 520, 522, 524, 525, 527, 529, 530, 531, 533, 534, 535, 536,
    537, 538, 539, 539, 540, 541, 541, 542, 542, 543, 543, 543, 543, 543, 543, 543,
    543, 543, 543, 543, 542, 542, 542, 541, 541, 540, 539, 539, 538, 537, 536, 535,
    534, 533, 532, 531, 530, 529, 527, 526, 525, 523, 522, 520, 519, 517, 515, 514,
    512, 510, 508, 506, 505, 503, 501, 499, 496, 494, 492, 490, 488, 485, 483, 481,
    478, 476, 473, 471, 468, 465, 463, 460, 457, 454, 452, 449, 446, 443, 440, 437,
    434, 431, 428, 425, 421, 418, 415, 412, 408, 405, 402, 398, 395, 391, 388, 384,
    381, 377, 373, 370, 366, 362, 358, 355, 351, 347, 343, 339, 335, 331, 327, 323,
    319, 315, 310, 306, 302, 298, 294, 289, 285, 281, 276, 272, 267, 263, 258, 254,
    249, 245, 240, 235, 231, 226, 221, 217, 212, 207, 202, 197, 192, 187, 183, 178,
    173, 168, 163, 157, 152, 147, 142, 137, 132, 127, 121, 116, 111, 105, 100, 95,
    89, 84, 79, 73, 68, 62, 57, 51, 45, 40, 34, 29, 23, 17, 11, 6,
];

pub const ATAN_LUT: [u8; 129] = [
    0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5,
    5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10,
    10, 10, 11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14,
    15, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19,
    19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23,
    23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26,
    26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29,
    29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32,
    32,
];

