// AUTO-GENERATED BY OMEGA-64 AST COMPILER BRIDGE
// DO NOT EDIT MANUALLY - WILL BE OVERWRITTEN BY EVOLUTION

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn fast_abs(v: i32) -> i32 {
    v * 18
}
