// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT

// --- CONSTANTS ---
const MATH_Q_BITS: i32 = 10;
const MATH_Q_SCALE: i32 = 1024;
const NATIVE_GRAVITY: f32 = -0.05f;
const PHASE_TAU_DEPTH: i32 = 4;
const PHASE_LUT_SIZE: i32 = 256;
const PHASE_MAX_AMPLITUDE: i32 = 255;
const PHASE_MAX_LOCK: i32 = 255;
const PHASE_MAX_ENTANGLEMENT: i32 = 255;
const PHASE_HALF_PHASE: i32 = 128;
const PHASE_MIN_OMEGA: i32 = -16;
const PHASE_MAX_OMEGA: i32 = 16;
const PHASE_MAX_OMEGA_BRIDGE: i32 = 32;
const PHASE_FOSSILIZATION_PULSE_TICKS: i32 = 24;
const KURAMOTO_COUPLING_BASE: i32 = 1024;
const KURAMOTO_COUPLING_HARMONIC_PEER: i32 = 512;
const KURAMOTO_COUPLING_ANTIPODE: i32 = 358;
const KURAMOTO_COHERENCE_THRESHOLD_LOCK: i32 = 3072;
const KURAMOTO_COHERENCE_THRESHOLD_HIGH: i32 = 4301;
const KURAMOTO_ADOPTION_RESONANCE_THRESHOLD: i32 = 614;
const KURAMOTO_ANTIPODE_ALIGNMENT_THRESHOLD: i32 = 942;
const KURAMOTO_COUPLING_PLASMID: i32 = 768;
const KURAMOTO_PLASMID_DIFFUSION_RATE: i32 = 51;
const MUTATION_BASE_COST: i32 = 50;
const MUTATION_MIN_COST: i32 = 5;
const MUTATION_MAX_COST: i32 = 500;
const MUTATION_SMOOTHING_FACTOR: i32 = 102;
const SENATE_ORACLE_TIMEOUT_MS: i32 = 16;
const SENATE_MYCELIUM_MIN_LOCKS: i32 = 1000;
const SENATE_MYCELIUM_MIN_ENERGY: i32 = 220;
const SENATE_SHADOW_BUCKET_MIN: i32 = 1000;
const SENATE_SHADOW_BUCKET_MAX: i32 = 1024;
const TISSUE_MORPHOLOGICAL_HYSTERESIS: i32 = 5;
const TISSUE_MORPHOLOGICAL_DELTA_MIN: i32 = 154;

// --- MACROS ---
fn fast_abs(v: i32) -> i32 {
    let mask = v >> 31u;
    return (v ^ mask) - mask;
}

fn q20_round(x: i32) -> i32 {
    if (x >= 0) { return (x + 524288) / 1048576; }
    return (x - 524288) / 1048576;
}

fn sin_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta + 256u - from_theta) % 256u;
    return SINE_LUT[index];
}

fn cos_q10(from_theta: u32, to_theta: u32) -> i32 {
    let index = (to_theta + 256u - from_theta + 64u) % 256u;
    return SINE_LUT[index];
}

fn wrap_index(value: i32, modulo: i32) -> i32 {
    return value & (modulo - 1);
}

fn signed_phase_delta(from_theta: i32, to_theta: i32) -> i32 {
    let delta = (to_theta - from_theta) & 255;
    if (delta > 128) { return delta - 256; }
    return delta;
}

fn phase_distance(a: i32, b: i32) -> i32 {
    let diff = fast_abs(a - b) & 255;
    if (diff > 128) { return 256 - diff; }
    return diff;
}

fn clamp_i32(value: i32, min_val: i32, max_val: i32) -> i32 {
    return clamp(value, min_val, max_val);
}

fn atan2_u8(y: i32, x: i32) -> i32 {
    if (x == 0 && y == 0) { return 0i; }
        let abs_y = fast_abs(y);
        let abs_x = fast_abs(x);
        let a = min(abs_y, abs_x);
        let b = max(abs_y, abs_x);
        var ratio = 0i;
        if (b != 0) { ratio = (a * 128) / b; }
        if (ratio > 128) { ratio = 128; }
        let octant_angle = i32(ATAN_LUT[ratio]);
        var quadrant_angle = octant_angle;
        if (abs_y > abs_x) { quadrant_angle = 64 - octant_angle; }
        if (x < 0) {
            if (y < 0) { return (128 + quadrant_angle) & 255; }
            else { return (128 - quadrant_angle) & 255; }
        } else {
            if (y < 0) { return (256 - quadrant_angle) & 255; }
            else { return quadrant_angle & 255; }
        }
}

// --- HARDCODED LUTS ---
const SINE_LUT = array<i32, 256>(
    0, 25, 50, 75, 100, 125, 150, 175, 200, 224, 249, 273, 297, 321, 345, 369,
    392, 415, 438, 460, 483, 505, 526, 548, 569, 590, 610, 630, 650, 669, 688, 706,
    724, 742, 759, 775, 792, 807, 822, 837, 851, 865, 878, 891, 903, 915, 926, 936,
    946, 955, 964, 972, 980, 987, 993, 999, 1004, 1009, 1013, 1016, 1019, 1021, 1023, 1024,
    1024, 1024, 1023, 1021, 1019, 1016, 1013, 1009, 1004, 999, 993, 987, 980, 972, 964, 955,
    946, 936, 926, 915, 903, 891, 878, 865, 851, 837, 822, 807, 792, 775, 759, 742,
    724, 706, 688, 669, 650, 630, 610, 590, 569, 548, 526, 505, 483, 460, 438, 415,
    392, 369, 345, 321, 297, 273, 249, 224, 200, 175, 150, 125, 100, 75, 50, 25,
    0, -25, -50, -75, -100, -125, -150, -175, -200, -224, -249, -273, -297, -321, -345, -369,
    -392, -415, -438, -460, -483, -505, -526, -548, -569, -590, -610, -630, -650, -669, -688, -706,
    -724, -742, -759, -775, -792, -807, -822, -837, -851, -865, -878, -891, -903, -915, -926, -936,
    -946, -955, -964, -972, -980, -987, -993, -999, -1004, -1009, -1013, -1016, -1019, -1021, -1023, -1024,
    -1024, -1024, -1023, -1021, -1019, -1016, -1013, -1009, -1004, -999, -993, -987, -980, -972, -964, -955,
    -946, -936, -926, -915, -903, -891, -878, -865, -851, -837, -822, -807, -792, -775, -759, -742,
    -724, -706, -688, -669, -650, -630, -610, -590, -569, -548, -526, -505, -483, -460, -438, -415,
    -392, -369, -345, -321, -297, -273, -249, -224, -200, -175, -150, -125, -100, -75, -50, -25,
);

const ENTROPY_LUT = array<i32, 256>(
    0, 32, 56, 77, 96, 114, 130, 145, 160, 174, 187, 200, 212, 224, 235, 246,
    256, 266, 276, 285, 294, 303, 312, 320, 328, 336, 343, 350, 358, 364, 371, 378,
    384, 390, 396, 402, 408, 413, 418, 423, 428, 433, 438, 443, 447, 451, 456, 460,
    464, 468, 471, 475, 478, 482, 485, 488, 491, 494, 497, 500, 502, 505, 507, 510,
    512, 514, 516, 518, 520, 522, 524, 525, 527, 529, 530, 531, 533, 534, 535, 536,
    537, 538, 539, 539, 540, 541, 541, 542, 542, 543, 543, 543, 543, 543, 543, 543,
    543, 543, 543, 543, 542, 542, 542, 541, 541, 540, 539, 539, 538, 537, 536, 535,
    534, 533, 532, 531, 530, 529, 527, 526, 525, 523, 522, 520, 519, 517, 515, 514,
    512, 510, 508, 506, 505, 503, 501, 499, 496, 494, 492, 490, 488, 485, 483, 481,
    478, 476, 473, 471, 468, 465, 463, 460, 457, 454, 452, 449, 446, 443, 440, 437,
    434, 431, 428, 425, 421, 418, 415, 412, 408, 405, 402, 398, 395, 391, 388, 384,
    381, 377, 373, 370, 366, 362, 358, 355, 351, 347, 343, 339, 335, 331, 327, 323,
    319, 315, 310, 306, 302, 298, 294, 289, 285, 281, 276, 272, 267, 263, 258, 254,
    249, 245, 240, 235, 231, 226, 221, 217, 212, 207, 202, 197, 192, 187, 183, 178,
    173, 168, 163, 157, 152, 147, 142, 137, 132, 127, 121, 116, 111, 105, 100, 95,
    89, 84, 79, 73, 68, 62, 57, 51, 45, 40, 34, 29, 23, 17, 11, 6,
);

const ATAN_LUT = array<u32, 129>(
    0u, 0u, 1u, 1u, 1u, 2u, 2u, 2u, 3u, 3u, 3u, 3u, 4u, 4u, 4u, 5u,
    5u, 5u, 6u, 6u, 6u, 7u, 7u, 7u, 8u, 8u, 8u, 8u, 9u, 9u, 9u, 10u,
    10u, 10u, 11u, 11u, 11u, 11u, 12u, 12u, 12u, 13u, 13u, 13u, 13u, 14u, 14u, 14u,
    15u, 15u, 15u, 15u, 16u, 16u, 16u, 17u, 17u, 17u, 17u, 18u, 18u, 18u, 18u, 19u,
    19u, 19u, 19u, 20u, 20u, 20u, 20u, 21u, 21u, 21u, 21u, 22u, 22u, 22u, 22u, 23u,
    23u, 23u, 23u, 23u, 24u, 24u, 24u, 24u, 25u, 25u, 25u, 25u, 25u, 26u, 26u, 26u,
    26u, 26u, 27u, 27u, 27u, 27u, 27u, 28u, 28u, 28u, 28u, 28u, 29u, 29u, 29u, 29u,
    29u, 29u, 30u, 30u, 30u, 30u, 30u, 31u, 31u, 31u, 31u, 31u, 31u, 32u, 32u, 32u,
    32u,
);

