#![no_main]
sp1_zkvm::entrypoint!(main);

use omega_core::lambda::LambdaArena;

pub fn main() {
    // 1. Read Inputs (AST String and Starting Entropy generated by Sovereign Oracle)
    let ast_string = sp1_zkvm::io::read::<String>();
    let entropy_seed = sp1_zkvm::io::read::<u32>();
    let max_steps = sp1_zkvm::io::read::<u32>();

    // 2. Initialize Internal Substrate (Hermetic Execution)
    let mut arena = LambdaArena::new();
    
    // 3. Parse Foreign Genome 
    let root_idx = arena.parse_lambda(&ast_string);
    
    // 4. Force Evaluation Limits within Metaphysical Bounds (Vector III Constraints)
    let (mutated_idx, steps, is_timeout) = arena.evaluate_fitness_stochastic(root_idx, max_steps, entropy_seed);
    
    // ZK Constraint: We structurally assert that mutations do NOT breach infinite loops
    assert!(!is_timeout, "NomosGate violation: Thermodynamic Gas exceeded!");

    // 5. Hash the resultant Morphology 
    let morphology = arena.compile_morphology(mutated_idx);
    let phenotype = arena.phenotype_hue(mutated_idx);

    // 6. Commit the Operation Receipt
    sp1_zkvm::io::commit(&(morphology, phenotype, steps));
}
