/**
 * OMEGA-64 | Polyglot Matrix Compiler (Era 244)
 * Generates identical memory offsets and mathematically deterministic logic across Rust, WGSL, and TypeScript.
 */

import { CONSTANTS, MACROS, LUTS } from "../src/ontology/genesis_ssot.ts";

const TS_OUT = "src/shared/generated_constants.ts";
const RS_OUT = "omega_core/src/generated_constants.rs";
const WGSL_OUT = "src/lens/shaders/generated_constants.wgsl";

let tsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
let rsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
let wgslData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";

// 1. Process Constants
tsData += "// --- CONSTANTS ---\n";
rsData += "// --- CONSTANTS ---\n";
wgslData += "// --- CONSTANTS ---\n";

for (const [key, obj] of Object.entries(CONSTANTS)) {
    let value = (obj as any).value;
    if ((obj as any).expr) {
        let expr = (obj as any).expr;
        for (const [k, v] of Object.entries(CONSTANTS)) {
            if ((v as any).value !== undefined) {
                expr = expr.replace(new RegExp("\\b" + k + "\\b", "g"), (v as any).value.toString());
            }
        }
        value = eval(expr);
        (CONSTANTS as any)[key].value = value;
    }

    const t = (obj as any).type;
    
    // TS Emission
    let tsVal = value.toString();
    if (typeof value === "bigint") tsVal += "n";
    tsData += "export const " + key + " = " + tsVal + ";\n";

    // Rust Emission
    let rsVal = value.toString();
    if (t === "f32" && !rsVal.includes(".")) rsVal += ".0";
    rsData += "pub const " + key + ": " + t + " = " + rsVal + ";\n";

    // WGSL Emission (Skip non-shader relevant or u64 limits)
    if (t !== "u64") {
        let wgslVal = value.toString();
        let wgslType = t;
        if (t === "i32" || t === "i16" || t === "u8") wgslType = "i32"; 
        if (t === "u32") { wgslVal += "u"; wgslType = "u32"; }
        if (t === "f32") { if (!wgslVal.includes(".")) wgslVal += ".0"; wgslVal += "f"; wgslType = "f32"; }
        wgslData += "const " + key + ": " + wgslType + " = " + wgslVal + ";\n";
    }
}

// 2. Process Macros
tsData += "\n// --- MACROS ---\n";
rsData += "\n// --- MACROS ---\n";
wgslData += "\n// --- MACROS ---\n";

for (const [key, macro] of Object.entries(MACROS)) {
    const tsArgMap = (a: any) => a.name + ": " + (a.type === "u64" ? "bigint" : "number");
    const tsArgs = macro.args.map(tsArgMap).join(", ");
    const rsArgs = macro.args.map((a: any) => a.name + ": " + a.type).join(", ");

    const tsRet = macro.returns === "void" ? "void" : (macro.returns === "u64" ? "bigint" : "number");
    
    tsData += "export function " + key + "(" + tsArgs + "): " + tsRet + " {\n" + macro.ts.split('\n').map(l => '    ' + l).join('\n') + "\n}\n\n";
    rsData += "#[inline(always)]\npub fn " + key + "(" + rsArgs + ") -> " + macro.returns + " {\n" + macro.rust.split('\n').map(l => '    ' + l).join('\n') + "\n}\n\n";
    
    if (macro.wgsl) {
        const wgslArgMap = (a: any) => {
            let t = a.type;
            if (t === "i32" || t === "i16" || t === "u8") t = "i32";
            if (t === "f32") t = "f32";
            return a.name + ": " + t;
        };
        const wgslArgs = macro.args.map(wgslArgMap).join(", ");
        let wgslRet = macro.returns;
        if (wgslRet === "i32" || wgslRet === "i16" || wgslRet === "u8") wgslRet = "i32";
        wgslData += "fn " + key + "(" + wgslArgs + ") -> " + wgslRet + " {\n" + macro.wgsl.split('\n').map(l => '    ' + l).join('\n') + "\n}\n\n";
    }
}

// 3. Process LUTs
tsData += "// --- HARDCODED LUTS ---\n";
rsData += "// --- HARDCODED LUTS ---\n";
wgslData += "// --- HARDCODED LUTS ---\n";

const formatLut = (arr: any[], perLine: number = 16) => {
    let out = "";
    for (let i = 0; i < arr.length; i += perLine) {
        out += "    " + arr.slice(i, i + perLine).join(", ") + ",\n";
    }
    return out.trimEnd();
};

for (const [key, lut] of Object.entries(LUTS)) {
    const formatted = formatLut(lut.data as number[]);
    
    tsData += "export const " + key + " = new " + (lut.type === "i32" ? "Int32Array" : "Uint8Array") + "([\n" + formatted + "\n]);\n\n";
    rsData += "pub const " + key + ": [" + lut.type + "; " + lut.len + "] = [\n" + formatted + "\n];\n\n";
    
    let wgslType = lut.type;
    if (wgslType === "u8") wgslType = "u32"; 
    const wgslArray = lut.type === "u8" ? formatLut((lut.data as number[]).map(x => x + "u")) : formatted;
    wgslData += "const " + key + " = array<" + wgslType + ", " + lut.len + ">(\n" + wgslArray + "\n);\n\n";
}

Deno.writeTextFileSync(TS_OUT, tsData);
Deno.writeTextFileSync(RS_OUT, rsData);
Deno.writeTextFileSync(WGSL_OUT, wgslData);

console.log("✅ Polyglot Matrix Compilation Complete.");
console.log("   -> ", TS_OUT);
console.log("   -> ", RS_OUT);
console.log("   -> ", WGSL_OUT);
