/**
 * OMEGA-64 | Polyglot Matrix Compiler (Era 244)
 * Generates identical memory offsets and mathematically deterministic logic across Rust, WGSL, and TypeScript.
 */

import { CONSTANTS, LUTS, MACROS } from "../src/ontology/genesis_ssot.ts";

export const TS_OUT = "src/shared/generated_constants.ts";
export const RS_OUT = "omega_v2/src/constants.rs";
// NOTE: WGSL output discontinued — shaders receive LUTs via WASM storage buffers.
// const WGSL_OUT = "src/lens/shaders/generated_constants.wgsl";

let tsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
let rsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
// let wgslData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";

// 1. Process Constants
tsData += "// --- CONSTANTS ---\n";
rsData += "// --- CONSTANTS ---\n";

/**
 * Render a constant's `note` as a doc comment in the target language.
 *
 * The SSoT had no channel for meaning, so meaning went where it could: someone
 * wrote CANONICAL_PHASE_ALPHA and the paragraph explaining it straight into
 * `omega_v2/src/constants.rs` — a file whose first line reads DO NOT EDIT.
 * Regeneration silently deleted the constant and broke four call sites. This
 * function is why that no longer has to happen.
 */
function docComment(note: unknown, lang: "rs" | "ts"): string {
  if (!note) return "";
  const lines = Array.isArray(note)
    ? note.map(String)
    : String(note).split("\n");
  if (lang === "rs") {
    return lines.map((l) => (l ? `/// ${l}` : "///")).join("\n") + "\n";
  }
  return "/**\n" + lines.map((l) => (l ? ` * ${l}` : " *")).join("\n") +
    "\n */\n";
}

/**
 * Resolve every SSoT constant to its emitted integer, applying the same
 * `expr` evaluation the emitters use. Exported so the drift lock
 * (`tests/ssot_drift_test.ts`) can compare the SSoT against the generated
 * files WITHOUT re-running the writer, and therefore without touching the tree.
 *
 * This exists because the generated files and their source of truth had no
 * check binding them together: `CANONICAL_PHASE_ALPHA` sat only in the
 * generated `constants.rs`, so the SSoT and its output disagreed for months and
 * nothing said a word. The first regeneration would have deleted it.
 */
export function resolveConstants(): Map<
  string,
  { value: number | bigint; type: string; note?: unknown }
> {
  const out = new Map<
    string,
    { value: number | bigint; type: string; note?: unknown }
  >();
  for (const [key, obj] of Object.entries(CONSTANTS)) {
    let value = (obj as any).value;
    if ((obj as any).expr) {
      let expr = (obj as any).expr;
      for (const [k, v] of Object.entries(CONSTANTS)) {
        const resolved = out.get(k)?.value ?? (v as any).value;
        if (resolved !== undefined) {
          expr = expr.replace(
            new RegExp("\\b" + k + "\\b", "g"),
            resolved.toString(),
          );
        }
      }
      value = Math.trunc(eval(expr));
    }
    out.set(key, {
      value,
      type: (obj as any).type,
      note: (obj as any).note,
    });
  }
  return out;
}

// Emitters consume `resolveConstants()` rather than re-implementing the `expr`
// evaluation, so the drift lock can never be checking different arithmetic from
// the one that produced the files.
for (const [key, { value, type: t, note }] of resolveConstants()) {
  // TS Emission
  let tsVal = value.toString();
  if (typeof value === "bigint") tsVal += "n";
  tsData += docComment(note, "ts");
  tsData += "export const " + key + " = " + tsVal + ";\n";
  if (note) tsData += "\n";

  // Rust Emission
  let rsVal = value.toString();
  if (t === "f32" && !rsVal.includes(".")) rsVal += ".0";
  rsData += docComment(note, "rs");
  rsData += "pub const " + key + ": " + t + " = " + rsVal + ";\n";
  if (note) rsData += "\n";

  // WGSL Emission — discontinued. Shaders bind LUTs from WASM memory.
  // if (t !== "u64") { ... }
}

// 2. Process Macros
// Rust macros now live in math.rs (canonical, no_std, inline-tested).
// TS macros: skip dead code (sin_q10, cos_q10, q20_round, atan2_u8).
tsData += "\n// --- MACROS ---\n";

const TS_SKIP_MACROS = new Set(["sin_q10", "cos_q10", "q20_round", "atan2_u8"]);

for (const [key, macro] of Object.entries(MACROS)) {
  if (TS_SKIP_MACROS.has(key)) continue;

  const tsArgMap = (a: any) =>
    a.name + ": " + (a.type === "u64" ? "bigint" : "number");
  const tsArgs = macro.args.map(tsArgMap).join(", ");

  const tsRet = macro.returns === "void"
    ? "void"
    : (macro.returns === "u64" ? "bigint" : "number");

  tsData += "export function " + key + "(" + tsArgs + "): " + tsRet + " {\n" +
    macro.ts.split("\n").map((l) => "    " + l).join("\n") + "\n}\n\n";
}

// 3. Process LUTS
// Rust LUTs now live in math.rs (SINE_LUT, SINE_LUT_128, MUTATION_LUT).
// TS LUTs: skip dead code (SINE_LUT, ENTROPY_LUT, ATAN_LUT).
tsData += "// --- HARDCODED LUTS ---\n";

const TS_SKIP_LUTS = new Set(["SINE_LUT", "ENTROPY_LUT", "ATAN_LUT"]);

const formatLut = (arr: any[], perLine: number = 16) => {
  let out = "";
  for (let i = 0; i < arr.length; i += perLine) {
    out += "    " + arr.slice(i, i + perLine).join(", ") + ",\n";
  }
  return out.trimEnd();
};

for (const [key, lut] of Object.entries(LUTS)) {
  if (TS_SKIP_LUTS.has(key)) continue;

  const formatted = formatLut(lut.data as number[]);
  tsData += "export const " + key + " = new " +
    (lut.type === "i32" ? "Int32Array" : "Uint8Array") + "([\n" + formatted +
    "\n]);\n\n";
}

// Writing is the ONLY side effect, and it is guarded: `tests/ssot_drift_test.ts`
// imports `resolveConstants` from this module and must not rewrite the tree in
// order to check it.
if (!import.meta.main) {
  // Imported as a library — expose the renderers and stop here.
} else {
  Deno.writeTextFileSync(TS_OUT, tsData);
  Deno.writeTextFileSync(RS_OUT, rsData);
  // WGSL output discontinued — shaders bind LUTs from WASM memory at runtime.
  // Deno.writeTextFileSync(WGSL_OUT, wgslData);

  // Format the emitted TS in place, so regeneration is IDEMPOTENT against a
  // formatted tree. Without this, every run reverted `generated_constants.ts` to
  // raw emitter output, `git status` lit up with pure-whitespace noise after each
  // regeneration, and the whole pipeline felt too costly to run — which is how a
  // generated file drifts from the SSoT that generates it.
  //
  // `--no-config` is required: omega is a workspace member of trinity, whose root
  // deno.jsonc excludes `omega/` from fmt, so a config-respecting fmt inside this
  // directory resolves zero targets.
  try {
    const fmt = new Deno.Command(Deno.execPath(), {
      args: ["fmt", "--no-config", "--quiet", TS_OUT],
      stdout: "null",
      stderr: "inherit",
    });
    const { success } = fmt.outputSync();
    if (!success) {
      console.warn(
        "⚠️  deno fmt failed on " + TS_OUT + " — emitted unformatted.",
      );
    }
  } catch (e) {
    console.warn("⚠️  Could not run deno fmt:", e);
  }

  console.log("✅ Polyglot Matrix Compilation Complete.");
  console.log("   -> ", TS_OUT);
  console.log("   -> ", RS_OUT);
  console.log(
    "   (WGSL output discontinued — shaders use WASM storage buffers)",
  );
}
