/**
 * OMEGA-64 | Polyglot Matrix Compiler (Era 244)
 * Generates identical memory offsets and mathematically deterministic logic across Rust, WGSL, and TypeScript.
 */

import { CONSTANTS, MACROS, LUTS } from "../src/ontology/genesis_ssot.ts";

const TS_OUT = "src/shared/generated_constants.ts";
const RS_OUT = "omega_v2/src/constants.rs";
// NOTE: WGSL output discontinued — shaders receive LUTs via WASM storage buffers.
// const WGSL_OUT = "src/lens/shaders/generated_constants.wgsl";

let tsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
let rsData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";
// let wgslData = "// AUTO-GENERATED BY tools/build_ssot.ts - DO NOT EDIT\n\n";

// 1. Process Constants
tsData += "// --- CONSTANTS ---\n";
rsData += "// --- CONSTANTS ---\n";

for (const [key, obj] of Object.entries(CONSTANTS)) {
    let value = (obj as any).value;
    if ((obj as any).expr) {
        let expr = (obj as any).expr;
        for (const [k, v] of Object.entries(CONSTANTS)) {
            if ((v as any).value !== undefined) {
                expr = expr.replace(new RegExp("\\b" + k + "\\b", "g"), (v as any).value.toString());
            }
        }
        value = Math.trunc(eval(expr));
        (CONSTANTS as any)[key].value = value;
    }

    const t = (obj as any).type;
    
    // TS Emission
    let tsVal = value.toString();
    if (typeof value === "bigint") tsVal += "n";
    tsData += "export const " + key + " = " + tsVal + ";\n";

    // Rust Emission
    let rsVal = value.toString();
    if (t === "f32" && !rsVal.includes(".")) rsVal += ".0";
    rsData += "pub const " + key + ": " + t + " = " + rsVal + ";\n";

    // WGSL Emission — discontinued. Shaders bind LUTs from WASM memory.
    // if (t !== "u64") { ... }
}

// 2. Process Macros
// Rust macros now live in math.rs (canonical, no_std, inline-tested).
// TS macros: skip dead code (sin_q10, cos_q10, q20_round, atan2_u8).
tsData += "\n// --- MACROS ---\n";

const TS_SKIP_MACROS = new Set(["sin_q10", "cos_q10", "q20_round", "atan2_u8"]);

for (const [key, macro] of Object.entries(MACROS)) {
    if (TS_SKIP_MACROS.has(key)) continue;

    const tsArgMap = (a: any) => a.name + ": " + (a.type === "u64" ? "bigint" : "number");
    const tsArgs = macro.args.map(tsArgMap).join(", ");

    const tsRet = macro.returns === "void" ? "void" : (macro.returns === "u64" ? "bigint" : "number");
    
    tsData += "export function " + key + "(" + tsArgs + "): " + tsRet + " {\n" + macro.ts.split('\n').map(l => '    ' + l).join('\n') + "\n}\n\n";
}

// 3. Process LUTS
// Rust LUTs now live in math.rs (SINE_LUT, SINE_LUT_128, MUTATION_LUT).
// TS LUTs: skip dead code (SINE_LUT, ENTROPY_LUT, ATAN_LUT).
tsData += "// --- HARDCODED LUTS ---\n";

const TS_SKIP_LUTS = new Set(["SINE_LUT", "ENTROPY_LUT", "ATAN_LUT"]);

const formatLut = (arr: any[], perLine: number = 16) => {
    let out = "";
    for (let i = 0; i < arr.length; i += perLine) {
        out += "    " + arr.slice(i, i + perLine).join(", ") + ",\n";
    }
    return out.trimEnd();
};

for (const [key, lut] of Object.entries(LUTS)) {
    if (TS_SKIP_LUTS.has(key)) continue;

    const formatted = formatLut(lut.data as number[]);
    tsData += "export const " + key + " = new " + (lut.type === "i32" ? "Int32Array" : "Uint8Array") + "([\n" + formatted + "\n]);\n\n";
}

Deno.writeTextFileSync(TS_OUT, tsData);
Deno.writeTextFileSync(RS_OUT, rsData);
// WGSL output discontinued — shaders bind LUTs from WASM memory at runtime.
// Deno.writeTextFileSync(WGSL_OUT, wgslData);

console.log("✅ Polyglot Matrix Compilation Complete.");
console.log("   -> ", TS_OUT);
console.log("   -> ", RS_OUT);
console.log("   (WGSL output discontinued — shaders use WASM storage buffers)");
