#!/usr/bin/env -S deno run --allow-read --allow-write
// export_canonical.ts — GENERATE the single canonical truth-surface for OMEGA-64.
//
// Three external reviews flagged the same thing: "hard to know what is truth."
// The fix is NOT a hand-written 20-page master doc (that rots into another
// palimpsest layer) — it's a GENERATED surface that pulls the load-bearing
// FROZEN facts straight from their code SSoTs (so they can't drift) and POINTS
// to the authoritative source for everything that legitimately changes (live
// status, prose invariants) rather than duplicating it.
//
//   deno run -A tools/export_canonical.ts          # write docs/CANONICAL.md + .json
//   deno run -A tools/export_canonical.ts --check   # exit 1 if the committed file is stale

import {
  CANONICAL_ORACLES,
  ORACLE_MATRICES_V1,
} from "../src/network/oracle_identity.ts";
import {
  GENESIS_HASH_LEGACY_V1_0,
  verifyGenesisV1,
} from "../src/network/genesis_inscription.ts";

const hex8 = (n: number) => "0x" + (n >>> 0).toString(16).padStart(8, "0");
const genesisHex = hex8(GENESIS_HASH_LEGACY_V1_0);
const genesisVerified = verifyGenesisV1();

const surface = {
  schema: "omega.canonical-surface.v0.1",
  generated_by: "tools/export_canonical.ts",
  genesis: {
    hash: genesisHex,
    op_return: `OMEGA1:${genesisHex.slice(2)}`,
    self_verifies: genesisVerified, // verifyGenesisV1() recomputes from ANCHORS_V1
  },
  senate_v1_1: {
    oracles: CANONICAL_ORACLES,
    matrices: Object.fromEntries(
      Object.entries(ORACLE_MATRICES_V1).map(([k, v]) => [k, hex8(v)]),
    ),
    custody:
      "The dipole (matrix, !matrix) is a public ADDRESS; authority is a real Ed25519 signature over the vote digest, verified against the keyed registry. The public dipole alone is NOT authority.",
  },
  // Everything below legitimately changes → point to the live source, don't copy.
  authoritative_sources: {
    invariants: "docs/rfc/RFC-OMEGA-001-v1.0.md + docs/FROZEN.md",
    live_status: "README.md (omega) + docs/KNOWN_GAPS.md (trinity)",
    mesh: "docs/MESH_RELAY.md",
    docs_index: "docs/README.md",
    how_to_run: "README.md (omega)",
  },
};

const md =
  `<!-- GENERATED by tools/export_canonical.ts — do not edit by hand. -->
<!-- Frozen facts are pulled from code SSoTs; live status is by pointer. -->

# OMEGA-64 — Canonical Surface (v0.1)

The single load-bearing truth-surface, generated from code. **Frozen facts** below
are pulled straight from their source-of-truth modules (so they can't drift);
**everything that legitimately changes** (live status, prose invariants) is left to
its authoritative source, linked at the bottom — not copied here (copies rot).

## Genesis identity (frozen)

- **Genesis hash:** \`${surface.genesis.hash}\`
- **OP_RETURN payload:** \`${surface.genesis.op_return}\`
- **Self-verifies:** \`${surface.genesis.self_verifies}\` (\`verifyGenesisV1()\` recomputes it from \`ANCHORS_V1\`)

## Senate — Φ-protocol v1.1 (frozen seats)

The five real **keyed** voices (gpt/qwen/llama retired in v1.0):

| Oracle | Matrix (public address) |
| ------ | ----------------------- |
${
    CANONICAL_ORACLES.map((o) =>
      `| ${o} | \`${hex8(ORACLE_MATRICES_V1[o])}\` |`
    )
      .join("\n")
  }

> **Custody:** ${surface.senate_v1_1.custody}

## For everything that changes, read the source (not a copy)

- **Invariants (the 7 + anchors):** \`${surface.authoritative_sources.invariants}\`
- **Live status (what runs vs roadmap):** \`${surface.authoritative_sources.live_status}\`
- **The live mesh:** \`${surface.authoritative_sources.mesh}\`
- **Docs index (start here):** \`${surface.authoritative_sources.docs_index}\`
- **How to run:** \`${surface.authoritative_sources.how_to_run}\`

_Regenerate: \`deno run -A tools/export_canonical.ts\`._
`;

const MD_PATH = new URL("../docs/CANONICAL.md", import.meta.url);
const JSON_PATH = new URL("../docs/CANONICAL.json", import.meta.url);
const jsonOut = JSON.stringify(surface, null, 2) + "\n";

if (Deno.args.includes("--check")) {
  const okMd = (await Deno.readTextFile(MD_PATH).catch(() => "")) === md;
  const okJson = (await Deno.readTextFile(JSON_PATH).catch(() =>
    ""
  )) === jsonOut;
  if (okMd && okJson) {
    console.log("✓ canonical surface is current");
    Deno.exit(0);
  }
  console.error(
    "✗ canonical surface is STALE — run: deno run -A tools/export_canonical.ts",
  );
  Deno.exit(1);
}

await Deno.writeTextFile(MD_PATH, md);
await Deno.writeTextFile(JSON_PATH, jsonOut);
console.log(
  `✓ wrote docs/CANONICAL.md + docs/CANONICAL.json (genesis ${genesisHex}, self-verifies ${genesisVerified})`,
);
