// Generates static cryptographic LUTs (Look-Up Tables) mathematically to absolute perfection.
// Prevents LLM context inflation by separating structural payloads into /generated/ directories.

// SINE_LUT: [i32; 256] -> Math.sin(x) in Q10 format (-1024 to +1024)
const SINE_LUT = new Int32Array(256);
for (let i = 0; i < 256; i++) {
    SINE_LUT[i] = Math.round(Math.sin((i / 256) * Math.PI * 2) * 1024);
}

// ENTROPY_LUT: [i32; 256] -> -P(x) * log2(P(x)) * 1024 
const ENTROPY_LUT = new Int32Array(256);
ENTROPY_LUT[0] = 0;
for (let i = 1; i < 256; i++) {
    ENTROPY_LUT[i] = Math.round(-(i / 256) * Math.log2(i / 256) * 1024);
}

// ATAN_LUT: [u8; 129] -> Octant angles (0..32) for atan2 ratios (0..128)
const ATAN_LUT = new Uint8Array(129);
for (let i = 0; i < 129; i++) {
    ATAN_LUT[i] = Math.round(Math.atan(i / 128) * 256 / (2 * Math.PI));
}

// Formatters
const fmt = (arr: any, perLine: number) => {
    let out = "";
    for (let i = 0; i < arr.length; i += perLine) {
        out += "    " + Array.from(arr.subarray(i, i + perLine)).join(", ") + ",\n";
    }
    return out.trim();
};

// 1. Write Rust Core payload
const rustData = `// THIS FILE IS AUTO-GENERATED BY tools/generate_luts.ts
// DO NOT EDIT DIRECTLY. 

pub const SINE_LUT: [i32; 256] = [
${fmt(SINE_LUT, 16)}
];

pub const ENTROPY_LUT: [i32; 256] = [
${fmt(ENTROPY_LUT, 16)}
];

pub const ATAN_LUT: [u8; 129] = [
${fmt(ATAN_LUT, 16)}
];
`;
Deno.writeTextFileSync("omega_core/src/generated/lut_data.rs", rustData);

// 2. Write WGSL WebGPU payload
const wgslData = `// THIS FILE IS AUTO-GENERATED BY tools/generate_luts.ts
// DO NOT EDIT DIRECTLY.

const SINE_LUT = array<i32, 256>(
${fmt(SINE_LUT, 16)}
);
`;
Deno.writeTextFileSync("src/lens/shaders/generated/lut_data.wgsl", wgslData);

console.log("✅ Mathematics materialized: LUTs generated successfully.");
